{
    0: Struct({
        1: U8(1),
        2: List([Struct({
                1: ShortString("109.244.198.14"),
                2: I16(8080),
                3: U8(1),
                4: Empty,
                5: Empty,
                6: U8(8),
                7: U8(1),
                8: ShortString("sz"),
                9: ShortString("others")
            }), Struct({
                1: ShortString("180.102.111.105"),
                2: I16(8080),
                3: U8(1),
                4: Empty,
                5: Empty,
                6: U8(8),
                7: U8(1),
                8: ShortString("sh"),
                9: ShortString("tel")
            }), Struct({
                1: ShortString("113.96.12.85"),
                2: I16(8080),
                3: U8(1),
                4: Empty,
                5: Empty,
                6: U8(8),
                7: U8(1),
                8: ShortString("sz"),
                9: ShortString("tel")
            }), Struct({
                1: ShortString("14.22.3.122"),
                2: I16(443),
                3: U8(1),
                4: Empty,
                5: Empty,
                6: U8(8),
                7: U8(1),
                8: ShortString("sz"),
                9: ShortString("tel")
            }), Struct({
                1: ShortString("42.81.193.250"),
                2: U8(80),
                3: U8(1),
                4: Empty,
                5: Empty,
                6: U8(8),
                7: U8(1),
                8: ShortString("tj"),
                9: ShortString("tel")
            }), Struct({
                1: ShortString("114.221.148.49"),
                2: I16(14000),
                3: U8(1),
                4: Empty,
                5: Empty,
                6: U8(8),
                7: U8(1),
                8: ShortString("sh"),
                9: ShortString("tel")
            }), Struct({
                1: ShortString("113.96.13.95"),
                2: I16(443),
                3: U8(1),
                4: Empty,
                5: Empty,
                6: U8(8),
                7: U8(1),
                8: ShortString("sz"),
                9: ShortString("tel")
            }), Struct({
                1: ShortString("42.81.192.211"),
                2: I16(8080),
                3: U8(1),
                4: Empty,
                5: Empty,
                6: U8(8),
                7: U8(1),
                8: ShortString("tj"),
                9: ShortString("tel")
            }), Struct({
                1: ShortString("101.91.42.98"),
                2: U8(80),
                3: U8(1),
                4: Empty,
                5: Empty,
                6: U8(8),
                7: U8(1),
                8: ShortString("sh"),
                9: ShortString("tel")
            }), Struct({
                1: ShortString("msfwifi.3g.qq.com"),
                2: I16(8080),
                3: U8(1),
                4: Empty,
                5: Empty,
                6: U8(8),
                7: Empty,
                8: ShortString("others"),
                9: ShortString("others")
            }), Struct({
                1: ShortString("42.81.172.207"),
                2: U8(80),
                3: U8(1),
                4: Empty,
                5: Empty,
                6: U8(8),
                7: U8(1),
                8: ShortString("tj"),
                9: ShortString("tel")
            })
        ]),
        3: List([Struct({
                1: ShortString("109.244.198.14"),
                2: I16(8080),
                3: U8(1),
                4: Empty,
                5: Empty,
                6: U8(8),
                7: U8(1),
                8: ShortString("sz"),
                9: ShortString("others")
            }), Struct({
                1: ShortString("180.102.111.105"),
                2: I16(8080),
                3: U8(1),
                4: Empty,
                5: Empty,
                6: U8(8),
                7: U8(1),
                8: ShortString("sh"),
                9: ShortString("tel")
            }), Struct({
                1: ShortString("113.96.12.85"),
                2: I16(8080),
                3: U8(1),
                4: Empty,
                5: Empty,
                6: U8(8),
                7: U8(1),
                8: ShortString("sz"),
                9: ShortString("tel")
            }), Struct({
                1: ShortString("14.22.3.122"),
                2: I16(443),
                3: U8(1),
                4: Empty,
                5: Empty,
                6: U8(8),
                7: U8(1),
                8: ShortString("sz"),
                9: ShortString("tel")
            }), Struct({
                1: ShortString("42.81.193.250"),
                2: U8(80),
                3: U8(1),
                4: Empty,
                5: Empty,
                6: U8(8),
                7: U8(1),
                8: ShortString("tj"),
                9: ShortString("tel")
            }), Struct({
                1: ShortString("114.221.148.49"),
                2: I16(14000),
                3: U8(1),
                4: Empty,
                5: Empty,
                6: U8(8),
                7: U8(1),
                8: ShortString("sh"),
                9: ShortString("tel")
            }), Struct({
                1: ShortString("113.96.13.95"),
                2: I16(443),
                3: U8(1),
                4: Empty,
                5: Empty,
                6: U8(8),
                7: U8(1),
                8: ShortString("sz"),
                9: ShortString("tel")
            }), Struct({
                1: ShortString("42.81.192.211"),
                2: I16(8080),
                3: U8(1),
                4: Empty,
                5: Empty,
                6: U8(8),
                7: U8(1),
                8: ShortString("tj"),
                9: ShortString("tel")
            }), Struct({
                1: ShortString("101.91.42.98"),
                2: U8(80),
                3: U8(1),
                4: Empty,
                5: Empty,
                6: U8(8),
                7: U8(1),
                8: ShortString("sh"),
                9: ShortString("tel")
            }), Struct({
                1: ShortString("msfwifi.3g.qq.com"),
                2: I16(8080),
                3: U8(1),
                4: Empty,
                5: Empty,
                6: U8(8),
                7: Empty,
                8: ShortString("others"),
                9: ShortString("others")
            }), Struct({
                1: ShortString("42.81.172.207"),
                2: U8(80),
                3: U8(1),
                4: Empty,
                5: Empty,
                6: U8(8),
                7: U8(1),
                8: ShortString("tj"),
                9: ShortString("tel")
            })
        ]),
        4: I32(1633005099),
        5: I16(14400),
        6: Empty,
        7: Empty,
        8: U8(2),
        9: U8(5),
        10: Empty,
        11: Empty,
        12: List([Struct({
                1: ShortString("109.244.129.15"),
                2: U8(80),
                3: U8(1),
                4: Empty,
                5: U8(3),
                6: U8(8),
                7: Empty,
                8: ShortString("sz"),
                9: ShortString("others")
            }), Struct({
                1: ShortString("114.221.144.22"),
                2: U8(80),
                3: U8(1),
                4: Empty,
                5: U8(3),
                6: U8(8),
                7: Empty,
                8: ShortString("sh"),
                9: ShortString("tel")
            }), Struct({
                1: ShortString("113.96.13.44"),
                2: U8(80),
                3: U8(1),
                4: Empty,
                5: U8(3),
                6: U8(8),
                7: Empty,
                8: ShortString("sz"),
                9: ShortString("tel")
            }), Struct({
                1: ShortString("119.147.190.37"),
                2: U8(80),
                3: U8(1),
                4: Empty,
                5: U8(3),
                6: U8(8),
                7: Empty,
                8: ShortString("sz"),
                9: ShortString("tel")
            }), Struct({
                1: ShortString("42.81.193.242"),
                2: U8(80),
                3: U8(1),
                4: Empty,
                5: U8(3),
                6: U8(8),
                7: Empty,
                8: ShortString("tj"),
                9: ShortString("tel")
            }), Struct({
                1: ShortString("180.102.59.50"),
                2: U8(80),
                3: U8(1),
                4: Empty,
                5: U8(3),
                6: U8(8),
                7: Empty,
                8: ShortString("sh"),
                9: ShortString("tel")
            }), Struct({
                1: ShortString("42.81.169.105"),
                2: U8(80),
                3: U8(1),
                4: Empty,
                5: U8(3),
                6: U8(8),
                7: Empty,
                8: ShortString("tj"),
                9: ShortString("tel")
            }), Struct({
                1: ShortString("42.81.169.105"),
                2: U8(80),
                3: U8(1),
                4: Empty,
                5: U8(3),
                6: U8(8),
                7: Empty,
                8: ShortString("tj"),
                9: ShortString("tel")
            })
        ]),
        13: List([Struct({
                1: ShortString("109.244.129.15"),
                2: U8(80),
                3: U8(1),
                4: Empty,
                5: U8(3),
                6: U8(8),
                7: Empty,
                8: ShortString("sz"),
                9: ShortString("others")
            }), Struct({
                1: ShortString("114.221.144.22"),
                2: U8(80),
                3: U8(1),
                4: Empty,
                5: U8(3),
                6: U8(8),
                7: Empty,
                8: ShortString("sh"),
                9: ShortString("tel")
            }), Struct({
                1: ShortString("113.96.13.44"),
                2: U8(80),
                3: U8(1),
                4: Empty,
                5: U8(3),
                6: U8(8),
                7: Empty,
                8: ShortString("sz"),
                9: ShortString("tel")
            }), Struct({
                1: ShortString("119.147.190.37"),
                2: U8(80),
                3: U8(1),
                4: Empty,
                5: U8(3),
                6: U8(8),
                7: Empty,
                8: ShortString("sz"),
                9: ShortString("tel")
            }), Struct({
                1: ShortString("42.81.193.242"),
                2: U8(80),
                3: U8(1),
                4: Empty,
                5: U8(3),
                6: U8(8),
                7: Empty,
                8: ShortString("tj"),
                9: ShortString("tel")
            }), Struct({
                1: ShortString("180.102.59.50"),
                2: U8(80),
                3: U8(1),
                4: Empty,
                5: U8(3),
                6: U8(8),
                7: Empty,
                8: ShortString("sh"),
                9: ShortString("tel")
            }), Struct({
                1: ShortString("42.81.169.105"),
                2: U8(80),
                3: U8(1),
                4: Empty,
                5: U8(3),
                6: U8(8),
                7: Empty,
                8: ShortString("tj"),
                9: ShortString("tel")
            }), Struct({
                1: ShortString("42.81.169.105"),
                2: U8(80),
                3: U8(1),
                4: Empty,
                5: U8(3),
                6: U8(8),
                7: Empty,
                8: ShortString("tj"),
                9: ShortString("tel")
            })
        ]),
        14: Bytes(b""),
        15: List([]),
        16: List([]),
        17: List([]),
        18: U8(2),
        19: I16(-200),
        20: ShortString("2021-09-30 16:31:39 deliverying a policy"),
        21: Empty
    })
}